// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

type SessionTokens = {
  access_token: string;
  refresh_token: string;
};

type LovableOAuthResult = {
  redirected?: boolean;
  error?: Error;
  tokens?: SessionTokens;
};

type LovableAuthModule = {
  createLovableAuth: () => {
    signInWithOAuth: (
      provider: "google" | "apple",
      options: SignInOptions,
    ) => Promise<LovableOAuthResult>;
  };
};

let lovableAuthPromise: Promise<ReturnType<LovableAuthModule["createLovableAuth"]> | null> | null = null;

async function getLovableAuth() {
  if (!lovableAuthPromise) {
    const moduleName = "@lovable.dev/cloud-auth-js";

    lovableAuthPromise = import(/* @vite-ignore */ moduleName)
      .then((module) => (module as LovableAuthModule).createLovableAuth())
      .catch(() => null);
  }

  return lovableAuthPromise;
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const lovableAuth = await getLovableAuth();

      if (!lovableAuth) {
        return {
          error: new Error("Social sign-in is not configured in this environment."),
        };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      if (!result.tokens) {
        return { error: new Error("Social sign-in did not return a valid session.") };
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }

      return result;
    },
  },
};
